// tailwind.config.js
import animate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./app/**/*.{ts,tsx,js,jsx}"],
  darkMode: ["class"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        serif: ["var(--font-serif)", "serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      boxShadow: {
        "2xs": "var(--shadow-2xs)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
      },
      letterSpacing: {
        tighter: "var(--tracking-tighter)",
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
        wider: "var(--tracking-wider)",
        widest: "var(--tracking-widest)",
      },
      spacing: {
        px: "1px",
        0: "0px",
        0.5: "calc(var(--spacing) * 0.5)",
        1: "var(--spacing)",
        1.5: "calc(var(--spacing) * 1.5)",
        2: "calc(var(--spacing) * 2)",
        2.5: "calc(var(--spacing) * 2.5)",
        3: "calc(var(--spacing) * 3)",
        3.5: "calc(var(--spacing) * 3.5)",
        4: "calc(var(--spacing) * 4)",
        5: "calc(var(--spacing) * 5)",
        6: "calc(var(--spacing) * 6)",
        7: "calc(var(--spacing) * 7)",
        8: "calc(var(--spacing) * 8)",
        9: "calc(var(--spacing) * 9)",
        10: "calc(var(--spacing) * 10)",
        11: "calc(var(--spacing) * 11)",
        12: "calc(var(--spacing) * 12)",
        14: "calc(var(--spacing) * 14)",
        16: "calc(var(--spacing) * 16)",
        20: "calc(var(--spacing) * 20)",
        24: "calc(var(--spacing) * 24)",
        28: "calc(var(--spacing) * 28)",
        32: "calc(var(--spacing) * 32)",
        36: "calc(var(--spacing) * 36)",
        40: "calc(var(--spacing) * 40)",
        44: "calc(var(--spacing) * 44)",
        48: "calc(var(--spacing) * 48)",
        52: "calc(var(--spacing) * 52)",
        56: "calc(var(--spacing) * 56)",
        60: "calc(var(--spacing) * 60)",
        64: "calc(var(--spacing) * 64)",
        72: "calc(var(--spacing) * 72)",
        80: "calc(var(--spacing) * 80)",
        96: "calc(var(--spacing) * 96)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-scale-in": {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-scale-in": "fade-scale-in 0.2s ease-out forwards",
      },
    },
  },
  plugins: [animate],
};