const fs = require('fs');
const path = require('path');

// Simple route tree generator
const routeTreeContent = `/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as GalleryRoute } from './routes/gallery'
import { Route as EditImageIdRoute } from './routes/edit.$imageId'

// Create the route tree
const routeTree = rootRoute.addChildren([
  IndexRoute,
  GalleryRoute,
  EditImageIdRoute,
])

export { routeTree }
`;

fs.writeFileSync(path.join(__dirname, 'routeTree.gen.ts'), routeTreeContent);
console.log('Route tree generated successfully!');
